# Generated by Django 3.2.4 on 2021-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_desconto', models.BooleanField(verbose_name='desconto')),
                ('porcentagem_desconto', models.IntegerField(verbose_name='porcentagem')),
                ('preco', models.CharField(max_length=10)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=400)),
                ('loja', models.CharField(max_length=30)),
            ],
        ),
    ]
