# Generated by Django 3.2.4 on 2021-07-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210703_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(max_length=500),
        ),
    ]
